### ISSUE TITLE
Add support for twig comments

### ISSUE THREAD

**Issue by mikesnoeren** [alstr/todo-to-issue-action#103]
As most of my projects make use of the twig templating engine it would be very nice to see support for comments in twig files.

Twig todo comments can look like this:

```twig 
{# TODO: Single line todo #}
{# @TODO: Single line todo #}
{# todo: Single line todo #}
{# @todo: Single line todo #}

{# TODO: Multi line todo 
  - lorem ipsum
  - dolor sit amet
#}

{# 
  TODO: Multi line todo 
  - lorem ipsum
  - dolor sit amet
#}
```

If someone can point me in the right direction I can try to make a PR for twig support myself.

**Comment by alstr** [comment]
Hey there. Making a PR to add a supported language is pretty straightforward:

* Add the language to `syntax.json` in the style of the existing entries. Both the examples you gave above would probably come under one entry, a block comment with a start and end marker.
* Add a test for the language to the tests file. If you can’t edit the Python file if you can just edit the diff with a mock code snippet I can add the test.

Thanks!

**Comment by mikesnoeren** [comment]
Unfortunately I did not have time to change any Python files, however, I was able to make a pull request with the other required changes: https://github.com/alstr/todo-to-issue-action/pull/106

**Comment by alstr** [comment]
All seems to work, thanks for the contribution!
