### ISSUE TITLE
Is `id` required when using this action?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [alstr/todo-to-issue-action#110]
In the readme it sets `id` to `todo`. Is this necessary in my workflow file?

https://github.com/alstr/todo-to-issue-action/blob/46584f64f7ddc01de0861d280fa550d5b3a29afc/README.md?plain=1#L41

**Comment by alstr** [comment]
You shouldn't need it by default, unless you want to reference it elsewhere in the workflow file. There are some more details here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
