### ISSUE TITLE
Include tag that points to the latest patched version

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [alstr/todo-to-issue-action#111]
Right now I can do `uses: alstr/todo-to-issue-action@v4.6.3`, but what if `v4.6.3` has a bug, and a newer version called `v4.5.4` fixes the bug? It would be convenient if I could do `uses: alstr/todo-to-issue-action@v4.6`. If there was a `v4.6` tag which was updated whenever a newer `v4.6.x` version was created, then the action would always use the version with the latest bug fixes.

**Comment by alstr** [comment]
Good idea, I'll add this to the list of enhancements.

**Comment by alstr** [comment]
I've added a `v4` major version tag that targets the latest v4 release. I could add a `v4.6` one but this should hopefully meet most requirements and makes things a bit simpler. You should now be able to do `uses: "alstr/todo-to-issue-action@v4"`. 😄
