### ISSUE TITLE
Scan all files the first time the action is run

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [alstr/todo-to-issue-action#112]
I added this action to my repository which has existing `TODO` comments. Because those files weren't diff, it did not create any issues from those `TODO`s. It would be nice if the action recognized that it was being added for the first time, and then scanned all files if it's the first time.

Here are some ways I can think of to know if it's the first time:
- If the file starting this workflow was created or modified in this commit
- The file previously did not contain `uses: alstr/todo-to-issue-action@v4.6.3`
- All files in `.github/workflows` previously did not contain `uses: alstr/todo-to-issue-action@v4.6.3`

**Comment by alstr** [comment]
Thanks for the suggestion. It could potentially be a slow operation and we'd need to update how parts of the action work. It's not impossible though. If anyone wants to work on it that would be great, otherwise I'll look into it more when I get chance.

**Comment by alstr** [comment]
I've added the ability to manually run the action to target either a commit range or a specific commit. Hopefully that should help with this scenario; it's the most straightforward solution I could come up with. It'll be released in the next version.
