### ISSUE TITLE
Action fails to check R files for TODOs

### ISSUE THREAD

**Issue by adamcagle** [alstr/todo-to-issue-action#128]
While R is listed as one of the supported languages, I'm unable to get the action to work with that language. The **TODO to Issue** step outputs:

*Could not check todo.R for TODOs as this language is not yet supported by default.*

I created an example repo [here](https://github.com/adamcagle/todo-action) where I've reproduced the issue.

**Comment by alstr** [comment]
Hey, thanks for that. I'm guessing it might be due to the uppercase extension. Could you try that in lowercase?

We probably should be case agnostic, but the action uses the extensions provided by Linguist, and there it's defined in lowercase:

https://github.com/github/linguist/blob/35159eef9aec4c5d0171a5bddf93a0f199e9724c/lib/linguist/languages.yml#L5356

Just an initial hunch.

**Comment by adamcagle** [comment]
Thanks for creating this action and for the quick reply to my issue! I think this will be an extremely useful workflow for me, and I'm looking forward to using it.

I tried changing the file extension from `.R` to `.r` and that does seem to have been part of the issue. I'm no longer getting a message about the language being unsupported, but the action did not generate any issues in the repo. I tried a few different things: I created a whole new file, added additonal comments, and tried using `#TODO` instead of `TODO:`, but none of those things seemed to make a difference. I also looked in the logs, but nothing stood out.

I suspect you are right that case agnostic is probably the right route to take, but maybe there would be some unforseen issues? Perhaps it could be implemented as an option at first to be on the safe side? The `.R` and `.r` extensions are both supported by R, but `.R` is much more common and is the officially recomended extension.

**Comment by alstr** [comment]
The file extension issue should be resolved now if you want to try that out in the latest version.

**Comment by adamcagle** [comment]
I just tested it out, and you are correct: `#TODO` doesn't work, but `# TODO` does. I also tried using the new version of the action, and it picked up the `.R` files without complaint. I think I'm in good shape now.

Much appreciated!

**Comment by alstr** [comment]
Excellent, thanks for the feedback. Any more issues do let me know. 😄
