### ISSUE TITLE
Project input

### ISSUE THREAD

**Issue by lmlima** [alstr/todo-to-issue-action#14]
Just like label input that would be great to have a project input to define a default project to TODO comments. Then, it will be possible to automatically create a project card.

**Comment by alstr** [comment]
This sounds like a great idea. I'm going to confess to not having really looked at projects much, so if anyone wants to see how this might work then that would be good! :smile:

**Comment by weibullguy** [comment]
I would second this and expand the suggestion to include adding labels as well.  Adding this action to my workflow has allowed me to get a bit more disciplined about "fixing" things when I should just open an issue and address them later.  Another use case where I've found this useful is identifying coding standards and requirements as I work.  Now I can document them without stopping to open a new issue.  Having labels automagically added when the issue is created would reduce even further the admin time spent managing issues.

**Comment by alstr** [comment]
Hey, thanks for the feedback. When you say add labels, would you want to hard code the labels in the workflow file? You could add whatever you wanted but they’d be the same for every issue. The alternative is some kind of system where you define the labels in the TODO and the action tries to parse them (like hashtags maybe).

**Comment by weibullguy** [comment]
Dynamically from the TODO.  My thinking is something along the lines of:

    [type:coding_std, status:in_progress, severity:normal]

or

    labels=type:coding_std, status:inprogress, severity:normal

at the end of the TODO causing the resulting issue to have the labels type:coding_std, status:in_progress, and severity:normal applied.  Personally, I'm more likely to have an understanding of this type of information as I write the TODO than which project or milestone I might assign the issue to.

I've been looking for an action to handle the labeling, but haven't found one that works for me yet.  If you or someone else reading this knows of one, the solution may be as simple as adding a link in the README file.

**Comment by alstr** [comment]
Thanks for the details. It shouldn't be too hard to do, so I might have a look at it over the weekend.

**Comment by alstr** [comment]
@weibullguy I've added this functionality in the latest version. See how you get on and if you have any comments please open a new issue. I'll leave this issue specifically for the project integration suggestion.

**Comment by Aniwax** [comment]
Hey guys, 

Great work out there :) But the functionality to specify the project is still not there. It would be great to have it.
Are you guys planning to add it?

**Comment by alstr** [comment]
Hey @Aniwax. This is next on my list to look at, so hopefully it’ll be added soon.

**Comment by alstr** [comment]
This has been added in `v4.0-alpha`. I've not tested organisation projects, only user projects, though support is there for both. The Readme should explain how it all works.

Please open a new issue if you encounter any problems or have any suggestions!
