### ISSUE TITLE
Stuck on v8.1

### ISSUE THREAD

**Issue by Indemnity83** [alstr/todo-to-issue-action#140]
I'm not sure what goes into creating an action, but it looks like although the code-base for this action has moved on to v4.9.1, the action.yml is still only pulling v4.8 each run because of this line:

https://github.com/alstr/todo-to-issue-action/blob/b50288792858dfc84690dbd7c1ecf99a4a1b52b8/action.yml#L6

This means the documentation doesn't align with the actual execution. Because the `workflow_dispatch` functionality wasn't added until after the 4.8 release, in 223e23516d238e0c0ac5005e6dcdfecbe5a261d5

Even the latest runs on this repository directly are 4.8: https://github.com/alstr/todo-to-issue-action/actions/runs/3756355414/jobs/6382338806

**Comment by alstr** [comment]
Good spot! Should be fixed now.
