### ISSUE TITLE
does this work with javascript codebases?

### ISSUE THREAD

**Issue by simkimsia** [alstr/todo-to-issue-action#15]
if so, how? 

```javascript
// TODO will this work?
```

what about

```javascript
/**
 * TODO
 *
 */
```

**Comment by simkimsia** [comment]
Now that I read this https://github.com/alstr/todo-to-issue-action#usage a little bit closer

This means I have to choose between `// TODO` and `* TODO` for javascript codebases

yes?

**Comment by alstr** [comment]
Hi. The action currently only supports one format, correct, so you would have to choose.

You could fork the repo and modify this behaviour pretty easily. If you want to submit a PR feel free.
