### ISSUE TITLE
Expand the md-support to Rmarkdown/Quarto files.

### ISSUE THREAD

**Issue by MBrede** [alstr/todo-to-issue-action#153]
The support for RMarkdown/Quarto should be easy to add (at least for comments outside of code chunks), since it uses the same comment-syntax as HTML.
This addition to `syntax.json` should do the trick:

```
  {
    "language": "RMarkdown",
    "markers": [
      {
        "type": "block",
        "pattern": {
          "start": "<!--",
          "end": "-->"
        }
      }
    ]
  },
```
I did also append and complete the markdown-tests locally.
If you are ok with it, I can open a PR.

**Comment by alstr** [comment]
No problem at all, thanks very much.
