### ISSUE TITLE
Todos with multi-line bodies showing with spaces

### ISSUE THREAD

**Issue by drkameleon** [alstr/todo-to-issue-action#156]
I've been using this action extensively. The problem is, when the TODO content body contains more than one line, the actual issue being created looks a bit weird and not that good. Here's an example: https://github.com/arturo-lang/arturo/issues/1122

Am I doing something wrong?

**Comment by alstr** [comment]
Set `AUTO_P` to `false` in your workflow file and that should sort it.

**Comment by drkameleon** [comment]
@alstr Awesome!! 

I don't know how it's possible to have missed it, but... I did! Thanks a lot! 😉
