### ISSUE TITLE
Do I need to fill in all the inputs?

### ISSUE THREAD

**Issue by simkimsia** [alstr/todo-to-issue-action#16]
Am experimenting with this GH Action.

https://github.com/alstr/todo-to-issue-action#inputs seems to suggest I can skip some of the inputs if not all the inputs.

Do I need to fill in  all?

**Comment by alstr** [comment]
with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "# TODO"
          COMMENT_MARKER: "#"

The first four are automatically set by GitHub, you should include them as above but not change them. The last two should also be included but can be changed.

In short, include all of them, but only modify the last two.
