### ISSUE TITLE
Escape characters inside of Title and Description

### ISSUE THREAD

**Issue by Christoph-Koschel** [alstr/todo-to-issue-action#161]
I'm really in love with this GH Action, but I fell into a bug.
When I write TODOs like this:

```typescript
function foo<T>(): T {
    // TODO Some Issue
    //   <T> must be of type bar
}
```

Then the `<T>` will be rendered as an HTML tag in Markdown, which is obviously wrong.

**Comment by alstr** [comment]
Thanks for the feedback. I want to improve how escaping is handled by the action, as mentioned in #146. I’ll look into this as soon as I can, but any PRs are welcome. :smile:
