### ISSUE TITLE
Can we support cuda files (.cu)

### ISSUE THREAD

**Issue by Gigatron** [alstr/todo-to-issue-action#166]
Got this mesage when running against my repo

```
Could not check cuda/msm/msm.cu for TODOs as this language is not yet supported by default.
```

Thanks!

**Comment by alstr** [comment]
I can't see any reason why not, if you're happy to submit a PR it should just be a case of editing `syntax.json` to add the appropriate comment syntax for that language and adding a couple of tests in the style of the existing. :smile:
