### ISSUE TITLE
how do i change the default label when the issue is created? is it by changing the id in the workflow.yml?

### ISSUE THREAD

**Issue by simkimsia** [alstr/todo-to-issue-action#17]
What does the id in the workflow.yml mean anyway?

![image](https://user-images.githubusercontent.com/245021/89037977-10cfae80-d372-11ea-89a3-095b322714e6.png)

See the label called `todo` Can I change it somehow? either in the workflow.yml or in the comments itself when I write it?

**Comment by alstr** [comment]
Please see the [workflow syntax](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsid):

> `jobs.<job_id>.steps.id`
> 
> A unique identifier for the step. You can use the id to reference the step in contexts. For more information, see "[Context and expression syntax for GitHub Actions."](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions)

In the context of this action, it doesn't allow the default label to modified.

The action does not allow for custom issue labels at the moment, but as mentioned previously, this is something that you could add relatively easily.

**Comment by alstr** [comment]
Worth noting that since commit f5290ad5ebe062bb5200990b7af72d70968cf3ae, the `todo` label is used to look up existing TODOs created by the action. If you change/remove the `todo` label when creating a new issue, you would probably want to modify this.
