### ISSUE TITLE
Issue body uses GitHub API base URL but should be regular GitHub

### ISSUE THREAD

**Issue by Clashsoft** [alstr/todo-to-issue-action#171]
See for example here: https://github.com/fujaba/fulib.org/issues/349. The link is neither rendered nicely, nor does it yield anything but an error when clicking.

The problem is here:

https://github.com/alstr/todo-to-issue-action/blob/77d9a65a69c4427858c666fe485b33b32b379b05/main.py#L119

Instead of `base_url` (which is set to `GITHUB_URL` env, which defaults to `github.api_url` action variable), it should be just the GitHub URL. Maybe an additional option is required.

**Comment by alstr** [comment]
Should hopefully be fixed by 7ad18c407689d234fb25588dc3127ef92ecf9522. I've just released a new version.
