### ISSUE TITLE
Label TODO is being appended to issue though alternative labels specified

### ISSUE THREAD

**Issue by mraht** [alstr/todo-to-issue-action#172]
In an ABAP test report I use the following line to specify a TODO:
<em>##FIX " Fix wrong number (0001 > 0003)
"assignees: mraht</em>

This generates the following issues:
![image](https://github.com/alstr/todo-to-issue-action/assets/99023738/4689fa47-e167-480b-92ca-6544da9ec6c1)

As one can see from the screenshot an additional TODO flag is being added though I defined default flags:
<em>IDENTIFIERS: '[{"name": "NEW", "labels": ["new"]}, {"name": "FIX", "labels": ["bug"]}, {"name": "OPT", "labels": ["opt"]}]'</em>

**Comment by alstr** [comment]
Hi. Thanks for the report. The `todo` label is automatically appended regardless of any custom labels as it is used by the action to check for any existing issues that it has created previously, to help avoid duplication. It might not be an ideal scenario but it's the way things work as it stands.

https://github.com/alstr/todo-to-issue-action/blob/5c97b3cb39d2d868453245e62bccc9a022b6d680/main.py#L97
