### ISSUE TITLE
Processing issue 1 of 1 Issue could not be closed/created

### ISSUE THREAD

**Issue by adriangalilea** [alstr/todo-to-issue-action#183]
Hello, 

New to github workflows and this particular action,

I was able to create my own automation before and managed to create issues, but I realised the complexity when my issues started to duplicate and decided to search a bit more and found this.

When I try to use it I get:
```
Processing issue 1 of 1
Issue could not be closed
```
or

```
Processing issue 1 of 1
Issue could not be created
```

I have no idea what it could be, I don't see much logs to share, I tried v4 and v4.13.

I also can attest I managed to create issues from my own script before, so not sure what's going on.

**Comment by adriangalilea** [comment]
Edit: this  seems  to fix it:
```diff
+permissions:
+  contents: read
+  issues: write

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: "TODO to Issue"
        uses: alstr/todo-to-issue-action@v4.13
+        with:
+          TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by adriangalilea** [comment]
Edit: this  seems  to fix it:
```diff
+permissions:
+  contents: read
+  issues: write

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: "TODO to Issue"
        uses: alstr/todo-to-issue-action@v4.13
+        with:
+          TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by alstr** [comment]
Thanks for the feedback. That shouldn't be required in the workflow file. You should just be able to do the following:

> 
If your workflow is executed but no issue is generated, check your repo permissions by navigating to Settings -> Actions (General) -> Workflow permissions and enable "Read and write permissions".
