### ISSUE TITLE
Minor doubt regarding default identifiers.

### ISSUE THREAD

**Issue by adriangalilea** [alstr/todo-to-issue-action#185]
After re-reading the README is not clear to me which identifiers it accepts by default, I think this can be easily fixed.

Doubts to address:
Does FIXME work by default?
If so, which others are included?

**Comment by alstr** [comment]
`TODO` is the only default identifier. Others can be added via the `IDENTIFIERS` input in `workflow.yml`.

https://github.com/alstr/todo-to-issue-action/blob/0f3f027d6945eb1eb6dc50a345bb23151b82cfbc/main.py#L306
