### ISSUE TITLE
Is there a way to limit the lines of code shown in issues created via GitHub Actions?

### ISSUE THREAD

**Issue by Wizely99** [alstr/todo-to-issue-action#197]
Sometimes, the entire file appears in the issue description. It would be helpful if the issue preview could be restricted to only include the function where the TODO is declared or at least a few lines.

**Comment by alstr** [comment]
You can use the `ISSUE_TEMPLATE` parameter in the workflow file.

This is briefly mentioned in the README; I'm sure there was more detail about it previously, so not sure why/when it was removed. Probably should update this.

Anyway, this is a string where you can insert the {{ title }}, {{ body }}, {{ url }} and {{ snippet }} placeholders to with any linebreaks and other text create a basic customised format.

**Comment by Wizely99** [comment]
@alstr Thank you it worked by removing the `{{ snippet }}` from the template.
```
...
 with:
          ISSUE_TEMPLATE: "{{ title }}\n{{ body }}\n{{ url }}"
```

**Comment by alstr** [comment]
Thanks, I've updated the README to include this.
