### ISSUE TITLE
[Suggestion] Add a link to the row where the TODO is as Issue comment

### ISSUE THREAD

**Issue by Insane96** [alstr/todo-to-issue-action#2]
E.g. a link like this
https://github.com/Insane96/IguanaTweaksReborn/blob/master/common/net/insane96mcp/iguanatweaks/modules/ModuleHardness.java#L83

**Comment by alstr** [comment]
That's a good idea, I'll take a look. 😄

**Comment by alstr** [comment]
This should now be possible in release `v1.0-beta`. It's not on the Marketplace yet due to a weird quirk but hopefully will be soon.
