### ISSUE TITLE
Unable to resolve action `alstr/todo-to-issue-action@v5`, unable to find version `v5`

### ISSUE THREAD

**Issue by neilime** [alstr/todo-to-issue-action#207]
The release v5 seams to be removed, all workflows using this action with tag v5 does not work anymore.

**Comment by alstr** [comment]
Hi there, you just beat me to creating the release. It should work now. :smile:

**Comment by neilime** [comment]
No, it does not work, v5 is still missing

**Comment by alstr** [comment]
Ah, I see what you mean. I'd created the v5.0 release but not the generic v5 release. It should work now.

**Comment by neilime** [comment]
Yes it works, thanks
