### ISSUE TITLE
TODOs with same text are confused

### ISSUE THREAD

**Issue by naps62** [alstr/todo-to-issue-action#216]
I merged a pull request where two different TODOs had the exact same text (similar to what I reported in #215 )

it seems the action got confused, and committed both issue URLs to the same place, instead of one for each

**Comment by alstr** [comment]
Can you share your workflow settings and a code example?

**Comment by rgalonso** [comment]
I think I've uncovered this issue too. In my case, it was the same text in the same file. Is that the case for you too, @naps62? If so, I've resolved it and, once I clean it up, I'll be submitting a PR to address it.

**Comment by alstr** [comment]
I think in the early days, when the action was simpler, there was an assumption that two TODOs in the same file with the same name was unlikely. So I can see how it would potentially not recognise both correctly, and if there was a way to improve things that would be good.
