### ISSUE TITLE
action not executed?

### ISSUE THREAD

**Issue by tricktresor** [alstr/todo-to-issue-action#22]
Hey there!
sorry, for maybe really dumb question... I'm very new to github.
Today I found this repo and added the todo2issue.yml file to my repo:
https://github.com/tricktresor/todo_action_test

Unfortunately it does not work as expected. :(

What am I doing wrong??

thanks for any hints

/edit:
just saw that I got emails:

~~~~~~~~~~~~~
Run failed for master (7df8b4b)
Repository: tricktresor/todo_action_test
Workflow: todo2issue
Duration: 48.0 seconds
Finished: 2020-10-19 19:54:30 UTC
[View results](https://github.com/tricktresor/todo_action_test/actions/runs/316216781)
Jobs:
•	[build](https://github.com/tricktresor/todo_action_test/runs/1277268746) failed (0 annotations)
~~~~~~~~~~~~~

but it does not help me any further...

Cheers
~Enno

**Comment by tricktresor** [comment]
Information about build:

Run alstr/todo-to-issue-action@v2.0
/usr/bin/docker run --name e5c35911858622f59446ba46ebd6368dacb9c_026c28 --label 1e5c35 --workdir /github/workspace --rm -e INPUT_REPO -e INPUT_BEFORE -e INPUT_SHA -e INPUT_TOKEN -e INPUT_LABEL -e INPUT_COMMENT_MARKER -e INPUT_CLOSE_ISSUES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/todo_action_test/todo_action_test":"/github/workspace" 1e5c35:911858622f59446ba46ebd6368dacb9c

**Comment by tricktresor** [comment]
Seems as if a "*" is not welcome as comment marker... 😢 
Tried instead with "$" and then the job runs and completes successfully, but no issue is created.

What else might be wrong?

**Comment by tricktresor** [comment]
Now it seems to work with \"

Issue created. 🥳

**Comment by alstr** [comment]
I'm not entirely sure what your issue is, but it's worth bearing in mind that TODOs cannot be added retrospectively. The TODO must be added in the pushed commit for an associated issue to be created. If the action fails for whatever reason but the commit is pushed, the TODOs won't be added next time around because they won't be in the next diff.

I've not tested using `"` but I could see how it could be problematic for escape-related reasons. I can't guarantee that it will work but if you've managed to get it going then great. :smile:
