### ISSUE TITLE
repeat of TODO comment line inserted instead of issue URL

### ISSUE THREAD

**Issue by rgalonso** [alstr/todo-to-issue-action#224]
If using non-standard capitalization of an identifier (e.g. "ToDo" instead of the standard "TODO"), instead of inserting the issue URL as a comment after the TODO, a verbatim copy of the TODO comment line is inserted.

When searching for an identifier (e.g. TODO, FIXME), a case-_insensitive_ search is performed. e.g. This will find "todo" in addition to "TODO". That's OK, because different people prefer different approaches to that[^1]. However, when it comes time to search for that line in the code (in order to insert the issue URL comment), the search is case-_sensitive_. This leads to the behavior noted in the first paragraph.

[^1]: We might want to consider making a case-sensitive match an option though. There could be projects where they strictly want to match "TODO" but not "todo", for instance.

**Comment by rgalonso** [comment]
@alstr, I've already got a solution for this. I just wanted to formally make an issue for this so we have traceability for all the changes I'm getting ready to push.

**Comment by alstr** [comment]
> @alstr, I've already got a solution for this. I just wanted to formally make an issue for this so we have traceability for all the changes I'm getting ready to push.

Thanks!
