### ISSUE TITLE
random line of existing source inserted into file

### ISSUE THREAD

**Issue by rgalonso** [alstr/todo-to-issue-action#225]
When a commit includes more than one **new** TODO in the same file, for all new TODOs after the first, instead of inserting the issue URL as a comment after the TODO, there will instead be a seemingly random line of existing source repeated. This line will be _near_ the new TODO, but not right beside it.

The reason for this is that the new lines are being inserted top-to-bottom. When the first is inserted, the app knows it needs to insert it at line X, and does so correctly. But when it tries to insert the next one at line Y (where Y > X), it doesn't find the expected TODO comment at line Y. That's because it's now at line Y+1 due to the earlier insertion. Despite this, the app blindly inserts a copy of the line it finds at Y, leading to the above behavior.

The solution is simply to process the file bottom-to-top. This way, as lines are inserted, they don't affect the line numbering of future insertions that will come _above_ the insertion.

**Comment by rgalonso** [comment]
@alstr, I've already got a solution for this. I just wanted to formally make an issue for this so we have traceability for all the changes I'm getting ready to push.

**Comment by rgalonso** [comment]
This is _probably_ a duplicate of #216, but we haven't gotten feedback from @naps62 on that issue to confirm it.

**Comment by naps62** [comment]
@rgalonso my apologies. I haven't been able to provide feedback because, due to this and other issues, I had to completely drop this action :/ since the repo where I used this is private, I couldnt easily provide an existing build log (was on my to-do list for a while, but life got in the way) 


From reading this one it seems it could very well be the same thing yes.

**Comment by rgalonso** [comment]
@naps62, I understand. If you could, we'd really appreciate any feedback you can provide on why the action didn't work for you. I'm a relatively new user of this myself. It's a good app, and I've been fixing a number of issues I've come across to make it even better. I'm working on getting those fixes integrated now. It may be the case that whatever issues you encountered have already been resolved.

Thanks for any feedback you can give. I understand concerns about a private repo, as I'm dealing with that myself.

**Comment by naps62** [comment]
Compiled what I know (and what I remember) here: https://github.com/alstr/todo-to-issue-action/issues/227

I know it's not much to go on, but hopefully it helps.
I still use this in a couple of smaller public repos, so perhaps it'll happen again in the future

**Comment by rgalonso** [comment]
This can be closed thanks to #228 and #237
