### ISSUE TITLE
issue URL not inserted if issue title contains regex characters

### ISSUE THREAD

**Issue by rgalonso** [alstr/todo-to-issue-action#226]
If the TODO comment's first line (i.e. what will become the issue title) contains any regex characters (for example `TODO: fix this (after first fixing issue #34)`, then the issue URL will not get properly inserted. (The line containing the TODO will just be repeated, as explained by #224/#225.)

This is happening because the `re.sub()` call which modifies the inserted line is not escaping the title.

**Comment by rgalonso** [comment]
@alstr, the solution is already implemented.

**Comment by alstr** [comment]
Another one I think is fixed.
