### ISSUE TITLE
issue labels aren't applied if TODO is not all caps

### ISSUE THREAD

**Issue by rgalonso** [alstr/todo-to-issue-action#230]
As noted in #224, matching the identifier (i.e. TODO) is done with a case-_insensitive_ search. However, when comparing against the identifier dictionary to apply labels, an exact match search is performed. This leads to a comment such as `ToDo` being identified as a TODO, but the issue labels are not applied.

**Comment by rgalonso** [comment]
Forgot to say it, but solution for this is implemented too and will probably be included with next PR

**Comment by alstr** [comment]
Think this is fixed now so I'll close.
