### ISSUE TITLE
false issue created if comment matches identifier in a substring

### ISSUE THREAD

**Issue by rgalonso** [alstr/todo-to-issue-action#234]
The identifier matching is not done using word breaks. Rather, it looks for either a whitespace character or a colon to follow the identifier. i.e. `TODO issue_title` and `TODO: issue_title` will both match, but `TODO` at the end of the line will not. However, this doesn't consider the possibility that non-whitespace characters precede the identifier. In other words, this means that due to this pattern match and case-insensitivity, using `FIX` as an identifier leads to the following comment being matched
```
  suffixed_str = base + suffix # add the suffix after the base string
```
The `fix` of `suffix` is seen as an identifier and `after the base string` is considered the issue title.

Word breaks should be used for pattern matching the identifier. i.e. `\b{identifier}\b`

**Comment by alstr** [comment]
I think this stems from the earliest version of the action, which didn't support other identifiers, where I must have been like "nothing can ever feature the word todo in". 😆

**Comment by rgalonso** [comment]
Haha, yeah, I would've thought so too. Imagine my surprise when it actually happened to me: "autodocumentation". I wouldn't consider that one word, but evidently someone does because there it is in my project!

**Comment by alstr** [comment]
Yeah, I'm sure there are cases, word boundaries are definitely the way to go.

**Comment by rgalonso** [comment]
I think the changes of v5.1.2 (and then refined in v5.1.3) have closed this. Feel free to re-open if there's a corner case I haven't considered.
