### ISSUE TITLE
Assignee Input

### ISSUE THREAD

**Issue by iammix** [alstr/todo-to-issue-action#25]
First of all, I would like to thank you for this amazing tool! To be honest, it saves me a ton of time.
A great Feature will be the ability to set asignees, in the way that you set the labels.
Looking forward for this update. Salute

**Comment by alstr** [comment]
Hey, thanks for the feedback. I'm glad you find it useful. That's a good idea and should be a relatively quick win. I'll try and have a look at it as soon as I get chance.

**Comment by alstr** [comment]
This should now be doable. I added in milestone support at the same time. :smile:
