### ISSUE TITLE
Extra whitelines in multiline comments

### ISSUE THREAD

**Issue by jucor** [alstr/todo-to-issue-action#31]
Thanks for a great tool! Just what I was looking for :)
Would you know how to avoid extra whitelines being added to multi-line TODOs, please? 
See for example https://github.com/jucor/krippendorff/issues/3 .
Thanks a lot :)

**Comment by alstr** [comment]
The action previously took each line to be a self-contained point, so formatted them as paragraphs.

I can see in your case your lines carry on from one another. To account for that, I've added a new setting called `AUTO_P`. It is `"true"` by default (same behaviour as before), but if you set it to `"false"` each line will be formatted as it is in your TODO. To add empty lines in that case, you could just add a `#` between them.

**Comment by jucor** [comment]
Amazing, thanks a lot! Indeed, hard-wrapping of the lines at 80 char prevents me from having only one line by self-contained point.
The fix works brilliantly, thank you!
