### ISSUE TITLE
Supporting Google coding style?

### ISSUE THREAD

**Issue by jucor** [alstr/todo-to-issue-action#32]
Hello! 
Would it be possible to support [Google styleguides's TODO](https://google.github.io/styleguide/cppguide.html#TODO_Comments) that Google recommends throughout all languages ([Python](https://google.github.io/styleguide/pyguide.html#312-todo-comments), [Shell](https://google.github.io/styleguide/shellguide.html#s4.4-todo-comments),  [Lisp](https://google.github.io/styleguide/lispguide.xml?showone=Attention_Required#Attention_Required), etc), please?

> TODOs should include the string TODO in all caps, followed by the name, e-mail address, bug ID, or other identifier of the person or issue with the best context about the problem referenced by the TODO. The main purpose is to have a consistent TODO that can be searched to find out how to get more details upon request. A TODO is not a commitment that the person referenced will fix the problem. Thus when you create a TODO with a name, it is almost always your name that is given.
> 
> ```c++
> // TODO(kl@gmail.com): Use a "*" here for concatenation operator.
> // TODO(Zeke) change this to use relations.
> // TODO(bug 12345): remove the "Last visitors" feature.
> ```

A former Googler, I've found this extremely helpful and use it all the time :) It is different from assignee.
I've had a stab at it by changing the `LABEL` input, but the look-ahead regex currently used requires constant-size patterns, so don't allow to capture the parenthesis group :/

**Comment by alstr** [comment]
This should now be possible without any configuration changes. Thanks for the suggestion.

**Comment by jucor** [comment]
It works brilliantly. Thanks a lot for that, and the remarkable reactivity!

**Comment by jucor** [comment]
Hi @alstr  -- sorry to be the bearer of bad news, but could it be that this broke the closing of issues when the corresponding TODO is deleted, at least for Google-style TODOs?
I have all my TODO Google-style, but they corresponding issues are not closed when I delete the TODO.

**Comment by alstr** [comment]
Oops - should be fixed in a6fcdf71b15ac124447a50f3ac5a49db67f87870. Thanks for pointing that out.

In the long term I might look at rewriting the action so that doesn't happen in future. It's grown a fair bit since the initial version, albeit on an ad hoc basis, and a class-based approach might make the code a bit clearer. Anyway, hope it works now.

**Comment by jucor** [comment]
Fantastic, thanks a lot! Will try it tomorrow when I close another one of these Todo and confirm that it works :)
