### ISSUE TITLE
Add support for multiple comment marker types

### ISSUE THREAD

**Issue by alstr** [alstr/todo-to-issue-action#35]
At the moment the action just accepts one comment marker, such as `#`.

This is fine for single-language projects, but where you have multiple languages you may need to use comments with a different syntax. For example, you might have a Python app that also has some CSS files `/* with comments like this */`.

One option would be to allow multiple markers in the config, but that could get a bit unwieldy, and you may not always know in advance.

As the action already performs a language lookup when processing each file in the diff, it may be good to use that to determine the comment syntax for the file in question. How we do that, without hardcoding everything (a huge and perhaps impractical task), I'm not sure at the moment.

A workaround at the moment is to set up the action to run multiple times, once for each comment marker type. Obviously this is not the most efficient solution, though.

**Comment by Wyfy0107** [comment]
I would love to have this feature also to use in Javascript files.

**Comment by alstr** [comment]
I’m just throwing this out there as a general question: in an IDE, when you comment out a code block via a shortcut, how does it know what syntax to use? My guess would be if this kind of behaviour could be reverse engineered (in other words, if we can determine the correct comment syntax based on the file type only) then dynamic comment markers would be doable.

**Comment by ChocolateLoverRaj** [comment]
@alstr I think it would be a good idea to have comment syntaxes based on file types. Then the r wouldn't be a need to have the `COMMENT_MARKER`.

**Comment by alstr** [comment]
> @alstr I think it would be a good idea to have comment syntaxes based on file types. Then the r wouldn't be a need to have the `COMMENT_MARKER`.

That’s what the goal is. I’m trying to figure out the most efficient way of doing it.

**Comment by ChocolateLoverRaj** [comment]
> I’m trying to figure out the most efficient way of doing it.
Maybe there could be a dictionary which has the comment and todo regexs with file extensions for keys.

**Comment by 0atman** [comment]
for now, I'd extend the 
```yaml
LABEL: "# TODO"
```

to
```yaml
LABELS:
 - "# TODO"
 - "// TODO"
```

If that would speed things up?

**Comment by alstr** [comment]
> for now, I'd be very happy to specify all the types I'm expecting, maybe just by extending the confg from:
> 
> ```yaml
> LABEL: "# TODO"
> ```
> 
> to
> 
> ```yaml
> LABELS:
>  - "# TODO"
>  - "// TODO"
> ```
> 
> Full file-type detection seems overkill to me, given there are about 5 common comment styles 😆

I have been thinking about that. I’m part way through developing a method that works similar to how @ChocolateLoverRaj mentioned.

The action already looks up the file type for Markdown styling, so I’m planning to use that to check the comment syntax. But yeah, there aren’t too many different formats, so hopefully that will make things more manageable.

I’ll see how testing goes, but hopefully will have something soon.

**Comment by joshmello** [comment]
@alstr I think that would work for my case

**Comment by alstr** [comment]
I have a completely rewritten version of the action almost ready. It processes comments dynamically, using the dictionary method mentioned previously. Will have it available for trying out soon.

**Comment by alstr** [comment]
I've released a beta version of the new action. Direct your workflow file to that release and remove any `LABEL` and `COMMENT_MARKER` inputs you have defined.

The action works off the accompanying `[syntax.json](https://github.com/alstr/todo-to-issue-action/blob/master/syntax.json)` file for identifying comments. Out of the box, this covers:

- Python
- YAML
- Ruby
- PHP
- C
- C++
- C#
- Java
- JavaScript
- Kotlin
- Objective-C
- SASS
- Swift
- HTML
- CSS

More languages can be added to the syntax file as we go, but I didn't want to overwhelm it straight away. There are some basic tests that can be run to check all these marker types are being picked up correctly.

So, theoretically, you should now be able to use line or block comments for various languages and they should all get picked up. I'm expecting a few issues here and there (it is a beta 😆) but hopefully we can iron them out.

**Comment by ChocolateLoverRaj** [comment]
@alstr Looks good. Just one fix is that for css comments are `/* comment */`, not like html comments.

**Comment by alstr** [comment]
I don't know how that happened. I've been looking at too many comments. 😆

**Comment by alstr** [comment]
I'm closing this as the feature is now implemented, but if any bugs are noticed please open new issues.
