### ISSUE TITLE
Wrapped comments supported?

### ISSUE THREAD

**Issue by ratnanil** [alstr/todo-to-issue-action#38]
In issue https://github.com/alstr/todo-to-issue-action/issues/35, @alstr mentions that

> At the moment the action just accepts one comment marker, such as #.

Am I reading this correctly, that wrapped comments such used in html (e.g. `<!-- TODO Revise this-->`) is currently not supported?

**Comment by alstr** [comment]
It _sort of_ works, I think, but it would include the closing tag in the issue title.

I agree it’s an issue worth solving, but as mentioned in #35 I would like to implement an altogether new way of processing comment markers; ideally one not tied to a specific/single marker definition in the action config. As part of this, wrapped comments would be supported. It’s something I’m actively thinking about but haven’t had chance to fully look at yet.

In the meantime, you could fork the app and amend the regex (or remove the trailing tag from the title) to accommodate the scenario you mentioned.

**Comment by alstr** [comment]
This will be supported in the upcoming release. Follow #35 for updates.
