### ISSUE TITLE
Hability to filter out branches

### ISSUE THREAD

**Issue by vis97c** [alstr/todo-to-issue-action#40]
I notice that you released this new version i'm lookinf fordward to implemented in my projects. The last version appeared to only work in master branch, is not clear from the docs if this would allow for different or at least pick a different one from the main one. Thanks again for your work. And let me know what would it take to implement such a feature.

**Comment by alstr** [comment]
Hey there. This should be possible if you set your `workflow.yaml` file to only run the action for specific branches.

Take a look at: https://github.com/alstr/todo-to-issue-action/issues/28#issuecomment-730512071

Let me know if that works for you.

**Comment by vis97c** [comment]
Cool, i will test it then. I'm closing this by the moment.
