### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by pilotak** [alstr/todo-to-issue-action#43]
Please add support for TypeScript TODOs. This is basically a javascript syntax. At the moment it shows following error
`Could not check src/routes.ts for TODOs as this language is not yet supported by default.`

**Comment by alstr** [comment]
Should work now, thanks.

**Comment by pilotak** [comment]
Thank you, could you please make a release?

**Comment by alstr** [comment]
Done. `v3.0.2-beta`. 😄
