### ISSUE TITLE
Add support for assigning repository projects, not just user and org level projects.

### ISSUE THREAD

**Issue by JimBledsoe** [alstr/todo-to-issue-action#57]
Support for user and org projects was recently added, but repositories also have projects.

From the Github API reference:
/repos/{owner}/{repo}/projects

Our organization, in particular, only use repo level projects.

**Comment by alstr** [comment]
Thanks for that. Please could you link to this endpoint in the API reference? I have not come across it before.

**Comment by JimBledsoe** [comment]
https://docs.github.com/en/rest/reference/projects#list-repository-projects

**Comment by alstr** [comment]
Thanks. This should be relatively simple to implement. I'll look at it at the next available opportunity.

**Comment by alstr** [comment]
On looking into this in more detail, the API only supports classic projects for repos. If you've not already assigned a classic project to your repo, you are no longer able to do it. Therefore, it seems quite difficult to implement and test this functionality. Ideally I would like to look to a more futureproof projects implementation, but not quite sure what that entails yet. If anyway has any ideas please feel free to suggest.
