### ISSUE TITLE
Duplicated TODOs

### ISSUE THREAD

**Issue by milewski** [alstr/todo-to-issue-action#68]
![image](https://user-images.githubusercontent.com/2874967/128289038-90191e30-d153-47c3-8a72-0156c969492a.png)

I have a lot of duplicated issues.. they keep getting created all the time... and once I close the PR only 1 usually gets auto closed.. all the others stay... I'm pretty sure this is due that we constantly rebase our PRs to keep our timeline linear, which changes the hashes from commits all the time... is there any workaround for it?

**Comment by JimBledsoe** [comment]
We configure our action to only fire this workflow on push to branches main or master.  While it's still a PR or branch, then rebase away.

It makes the most sense to us, because if something is still in a PR or earlier and nothing committed to main, then it's not "real" yet.  We may change our minds half a dozen times about what remains as TODOs versus what we take care of right then and there in the branch.  No more dupes.

**Comment by JimBledsoe** [comment]
We also started using this action bubkoo/potential-duplicates early on with a high threshold of 0.90, and even though we don't need it any more, we kept it because it was so handy.

**Comment by milewski** [comment]
Hey @JimBledsoe, that makes totally sense, yeah I think if I change it to only trigger on merge instead of every push would be the ideal in my case, thanks.

**Comment by alstr** [comment]
Thanks for that. Rebasing is a bit tricky, but I’m seeing what can be done to improve things in #62.

Also, not sure if you’re using the latest version, but the action _shouldn’t_ recreate a TODO that already exists with the same contents:

https://github.com/alstr/todo-to-issue-action/blob/3fd212fda154273498916d48fdad504a09c6f67d/main.py#L117

Is that check not working as expected?

**Comment by JimBledsoe** [comment]
I'm using 4.0.7 and when we had it on any push, it would create one when it was created on the branch, then create another one when we merged it to main.

I can't remember if it was making dupes on a regular merge or just a squash merge, but a squash merge was definitely making an exact duplicate.

**Comment by alstr** [comment]
Thanks. There’s a chance that when it ran the second time, the issue didn’t exist, but I don’t know for sure. I’ll do some further testing around how it handles duplicate titles though.
