### ISSUE TITLE
Check how the action handles issues with duplicate titles/content

### ISSUE THREAD

**Issue by alstr** [alstr/todo-to-issue-action#70]
Standard behaviour should be to ignore, but reports in #68 suggest this is potentially not happening.

**Comment by JimBledsoe** [comment]
I noticed in a duplicate that this action duplicated yesterday had significant reconfiguration of the enclosing text such that the content looked significantly different.  So different that the duplicate detector did not see it as duplicate, either.

In this case, it was not a rebase or squash or anything like that.  It was code moved between files and within context around it. 
 Just form the diffs itself, I don't see anything relating to the context around the comment itself that would even have remotely looked the same to code.  But the content of the comment block itself was identical.

**Comment by alstr** [comment]
I've made an update that excludes the surrounding code block from the check to see if an issue already exists. Also, if an item appears in the diff as both a deletion and addition, it is ignored. Hopefully that helps.

**Comment by JimBledsoe** [comment]
Oh yay.  Migrating to 4.1 now.  Will give some feedback in a week or so.  Bravo.

**Comment by JimBledsoe** [comment]
Version 4.1 worked well all week.

**Comment by alstr** [comment]
Good to hear, thanks for the feedback!
