### ISSUE TITLE
auto assign

### ISSUE THREAD

**Issue by baronTommy** [alstr/todo-to-issue-action#84]
Hello😀

I'd like to see a setting that automatically assigns users who have been pushed.

It is not an assignment in the comments.👀
https://github.com/marketplace/actions/todo-to-issue#assignees

**Comment by alstr** [comment]
Thanks for the suggestion. This is definitely doable relatively easily, as similar functionality is already in place for labels. I will add this to the list.

**Comment by alstr** [comment]
Do you mean you want to automatically assign the person who pushes the commit, or a user defined in the workflow file?

**Comment by baronTommy** [comment]
Thanks for the reply 😀

I would like you to assign someone who has pushed.

I used to use [this](https://github.com/marketplace/todo) one, but I prefer GithubActions.


I would like to have this feature.

> https://github.com/JasonEtco/todo#available-options
> autoAssign

---

https://github.com/baronTommy/interactive-commit/issues/6

![2021-11-04 at 22 13](https://user-images.githubusercontent.com/16768208/140319789-2c6b13cd-e5a6-4bc7-9758-fef5c19fc1fd.png)
.

**Comment by alstr** [comment]
I've added in something similar to what you suggested, let me know how it works for you.

**Comment by baronTommy** [comment]
https://github.com/baronTommy/are/issues/13

It works as expected.


![file](https://user-images.githubusercontent.com/16768208/140497990-6a60b608-cd96-43e9-be89-788a1f776a66.gif)
