### ISSUE TITLE
link issues to close when a PR is created

### ISSUE THREAD

**Issue by DetachHead** [alstr/todo-to-issue-action#98]
it would be cool if instead of just closing issues once a PR is merged, it could automatically add the issues that will be closed to the Linked issues of the PR so you can easily see which TODO's the PR resolves

![image](https://user-images.githubusercontent.com/57028336/148953446-84ce67f2-891f-42d0-83f1-b1f637fdb8d7.png)

github will automatically close any issues linked here once the PR gets merged

**Comment by alstr** [comment]
Good idea. Do you know where the functionality to do this is in the API? Had a quick look through the endpoints for PRs and issues but didn't see anything.

**Comment by DetachHead** [comment]
not sure, i'm not familiar with the github api sorry

**Comment by DetachHead** [comment]
perhaps it's possible to set up an action to run when a PR is created/pushed to with a bot that edits the description of a PR to add "closes #xxx" to it

**Comment by alstr** [comment]
Potentially. Keeping track of all the issues might be a bit tricky. I'm guessing any time a TODO is removed you're assuming that the PR closes that related issue?

I'm not sure how it would work but I'll think about it. If anyone else wants to chip in with suggestions, feel free.

**Comment by ChocolateLoverRaj** [comment]
> any time a TODO is removed you're assuming that the PR closes that related issue?

@alstr I think this is exactly what this issue is about 👍

**Comment by alstr** [comment]
I've added support for this in the next major version. You'd just need to add `PR_NUMBER: ${{ github.event.pull_request.number }}` to `env` in your workflow. If you try it let me know how you get on.
